# Generated by Django 4.1.5 on 2023-01-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikes_name', models.CharField(max_length=255)),
                ('bikes_spec', models.CharField(max_length=255)),
                ('bikes_image', models.ImageField(upload_to='bikes')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='dep_name',
        ),
        migrations.DeleteModel(
            name='departments',
        ),
    ]
