# Generated by Django 4.1.5 on 2023-01-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_inventory_remove_doctors_dep_name_delete_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_on',
            new_name='Booked_on',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='Booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_phone',
            new_name='Phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='doc_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='Model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.inventory'),
            preserve_default=False,
        ),
    ]
