# Generated by Django 4.1.5 on 2023-01-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_booked_on_booking_booked_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Booking_date',
        ),
    ]
