# Generated by Django 4.1.5 on 2023-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_booking_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.AddField(
            model_name='booking',
            name='Booking_date',
            field=models.DateField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
