# Generated by Django 4.1.5 on 2023-01-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_doctors_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Booking_date',
        ),
    ]
